name: scrape

on:
  schedule:
    # Every hour at :06 and :36 (not on the dot)
    - cron: "6,36 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Random delay (0–300s)
        run: |
          DELAY=$((RANDOM % 301))
          echo "⏳ Waiting $DELAY seconds before scraping..."
          sleep $DELAY

      - name: Run scraper with retries
        run: |
          n=0
          until [ $n -ge 3 ]
          do
            echo "🚀 Attempt $((n+1))..."
            node .github/workflows/scrape-getdaytrends.js && break
            n=$((n+1))
            echo "⚠️ Scraper failed. Retrying in 10s..."
            sleep 10
          done

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull --rebase
          git add latest_full50.json history/ || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update trends [skip ci]"
            git push
          fi
